services:
  - type: web
    name: ownership-api
    runtime: docker
    plan: free
    repo: https://github.com/MariaEarly/ownership-mvp
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ownership-db
          property: connectionString
      - key: ARTIFACT_DIR
        value: /tmp/artifacts
      - key: SIRENE_API_KEY
        sync: false
      - key: SIRENE_BASE_URL
        value: https://api.insee.fr/api-sirene/3.11

databases:
  - name: ownership-db
    plan: free
    ipAllowList: []
